### ISSUE TITLE
Renovación y Elección de Cargos

### ISSUE THREAD

**Issue by MrTommyGuns** [UC3Music/Gestiones-y-Movidas#1]
Como hablamos en la reunión del día 20-9-18 toca renovar los cargos de _Presidente/a_, _Secretario/a_ y _Tesorero/a_.
Para lo cual realizaremos una votación online (probablemente por el Telegram de la Asociación).

A continuación nombraré a las personas que se presentan para cada cargo:

**-Presidente:** David, Pablo
**-Secretario:** Tomás.
**-Tesorero:** JorFru

_**Si alguien más quiere presentarse** para alguno de los cargos está a tiempo antes de que se realicen las votaciones._
También se puede crear el cargo de subpresi. Para que no os peleéis.

**Comment by MrTommyGuns** [comment]
Creo que tras una semana el que quiera presentarse ya lo ha podido hacer...
¿Procedemos a realizar la votación?  ¿O esperamos a quedar otra vez con los nuevos?

**Comment by David-Estevez** [comment]
El método que seguimos en ASROB es montar un Google Form con las opciones. No es la única opción, pero lo comento como dato.

Una vez elegido el método podemos hacer la votación.

**Comment by JorFru** [comment]
El método Google Form es mi opción preferida para temas importantes. Y dejaría el método @vote de Telegram para las decisiones más livianas.

**Comment by MrTommyGuns** [comment]
Me parece bien hacer un Form y dejar el bot para cosas más del día a día como comenta Jorfru

**Comment by JorFru** [comment]
Jey!
Yo creo que casi ni hace falta votar.

Sólo hay una opción, y como todos somos Juan Romo, nos podemos quedar.

Pero si consideráis la opción, montamos un form.

**Comment by MrTommyGuns** [comment]
Pues sí, votar teniendo solo una persona para cada cargo es un poco tontería... Y al final los cargos son por poner nombre a los responsables de cada cosa pero nos organizamos a nuestro rollo haciendo cada uno lo que puede y tal, así que como veáis...
Si se vota será solo porque quede formalizado, no por nada más

**Comment by David-Estevez** [comment]
¿Montamos votación entonces o no?

**Comment by L4g0** [comment]
¿@David-Estevez sigue interesado en ser presidente y conseguir el monopolio de ASROB-UC3Music o prefiere aliviar peso de trabajo?

En ese caso me presento a presidente tb lol. _(Por favor quitadme de tesorero, estoy sufriendo)_.

Sea como sea, deberíamos dejar fijado esto cuanto antes, me pone nervioso ver tanta issue abierta xD



![image](https://user-images.githubusercontent.com/23212123/48986873-219a3c80-f11a-11e8-94cc-57dc4511cb0a.png)
### Por favor, no pongan a Pablo de tesorero, dadle la presidencia (este gatito estará triste si no es así).

_Lo siento por tardar tanto :c_

**Comment by JorFru** [comment]
Yo me presento de tesorero!

**Comment by David-Estevez** [comment]
LOL! Sigo interesado en el puesto de presi, sí, y voto a Pablo como tesorero :laughing: 

¿Montamos la votación?

**Comment by JorFru** [comment]
@David-Estevez @L4g0 ¿habilitamos el cargo de subpresi o nos la jugamos todo a una carta?
@L4g0 ¿te quito como candidato de tesorero entonces?


La votación sería:
Presi: elegir sr. Lago o sr. Estévez
Secre: @MrTommyGuns como única opción
Tesorería: @JorFru como única opción
¿Correcto?

**Comment by L4g0** [comment]
Yo veo bien que estemos todos en la junta, que al fin y al cabo somos los que estamos haciendo cosas. Me da igual como tesorero que subpresi, el otro día me motivé un poco xD

**Comment by JorFru** [comment]
Pues anímate a presentarte a los dos.

**Comment by David-Estevez** [comment]
Vamos a votar ya que esto lleva abierto desde Septiembre :laughing: :laughing: :rofl: :rofl:

**Comment by JorFru** [comment]
https://goo.gl/forms/MNmuCl9J26KD5d4b2


revisad si está todo correcto

**Comment by MrTommyGuns** [comment]
Correcto!

**Comment by L4g0** [comment]
@JorFru seems right

**Comment by MrTommyGuns** [comment]
Eso sí, todos con nombre y apellidos y yo "Tomás el pistolas" jajajajajaja brutaal!! 😂😂😂

**Comment by JorFru** [comment]
> Eso sí, todos con nombre y apellidos y yo "Tomás el pistolas" jajajajajaja brutaal!! joyjoyjoy

Perdona, es que no me acordaba de tus apellidos

**Comment by L4g0** [comment]
![image](https://user-images.githubusercontent.com/23212123/49876204-2867c580-fe23-11e8-8f18-627edb8e8c8c.png)

Con altísima participación los resultados son los siguientes:
**Presidente:** @L4g0 
**Subpresidente (_presi en la sombra_):** @David-Estevez 
**Secretaría:** @MrTommyGuns 
**Tesorería:** @JorFru
