### ISSUE TITLE
UC3Music na OSHWDem18

### ISSUE THREAD

**Issue by JorFru** [UC3Music/Gestiones-y-Movidas#10]
Tenemos a ASROB y a UC3Music apuntados a la OSHWDem 2018, lo cual implica 2 plazas por cada asociación + 1 (?) plaza de un taller de UC3Music (esto lo tiene que confirmar @JorFru ).

Como ya hemos ido otros años y nos conocen, @David-Estevez  y yo estamos llevando a cabo las gestiones con ellos. @David-Estevez  y yo podemos estar en cualquiera de las 3 cosas (stand ASROB, stand UC3Music o taller), así que quedarían otras 3 plazas a repartir entre ASROB y UC3Music. Los que quieran ir que se manifiesten por aquí.

# EDIT Fechas y horarios
1. Opción 1:

    - Salida el jueves (ya que el viernes es fiesta en Madrid (Aunque no fiesta en la uni))
    - Fiesta el jueves: los madrileños con los gallegos que se atrevan a salir el jueves aunque el viernes tengan que trabajar.
    - Fiesta el viernes
    - OSHWDem sábado
    - Fiesta sábado.
    - Volver el domingo a mediodía, llegar sobre las 20h.

2. Opción 2:

    - Salida el viernes
    - Fiesta el viernes
    - OSHWDem sábado
    - Fiesta sábado
    - Volver el domingo a mediodía, llegar sobre las 20h.

**Comment by David-Estevez** [comment]
Yo! Yo! Yo! :man_cartwheeling:

**Comment by L4g0** [comment]
Es el día 10, ¿qué día se saldría de Madrid y se volvería?

**Comment by JorFru** [comment]
La noche del 9 se cena y se hace una prefiesta.
Yo haría los cálculos para llegar el viernes 9 como muy tarde a las 22h.
Idealmente a las 21h o antes.

**Comment by L4g0** [comment]
¿y volver el sábado o el domingo?

**Comment by JorFru** [comment]
La fiesta imperdible es la noche del sábado 10. Vuelta el domingo, y lo más probable es que la salida sea hacia mediodía. Llegaremos de noche casi seguro el domingo.

**Comment by MrTommyGuns** [comment]
Yo tengo examen el 9 a última hora así que no puedo

**Comment by JorFru** [comment]
He añadido información sobre las fechas y horarios en el primer comentario de la issue.

**Comment by JorFru** [comment]
`1 (?) plaza de un taller de UC3Music (esto lo tiene que confirmar @JorFru ).`
Confirmado @David-Estevez

**Comment by L4g0** [comment]
Asistencia realizada con éxito, nos vemos el año que viene
