### ISSUE TITLE
Reunión con África post-Semana de Asociaciones

### ISSUE THREAD

**Issue by JorFru** [UC3Music/Gestiones-y-Movidas#11]
## Martes, 23 de Octubre a las 13:30 en Getafe, aula 9.1.4

Esta reunión es importante, recordad que en la Semana de Asociaciones no pudimos explicar nuestro proyecto porque se cancelaron las dos actividades donde íbamos a participar: bienvenida de la semana (con una presentación breve) y ~la charla "conoce ASROB" con spam del duro.~ (inserte aquí actividades de UC3Music)
Recordad #8

**Comment by JorFru** [comment]
Yo no puedo ir porque tengo un curso de 13 a 15 y después clases

**Comment by MrTommyGuns** [comment]
Jorfru, te has liado, este es el repo de Uc3Music jajaja
Que si es importante también deberíamos ir supongo... 🙄
A mi me fastidia porque tengo 2 exámenes tochos esta semana, no los llevo nada bien y tengo clase de 3 a 9...

**Comment by MrTommyGuns** [comment]
Me he liado y pensaba que era el lunes, siendo el martes, si nadie puede ir, quizas pueda hacer el esfuerzo e ir yo... Pero no puedo asegurar nada, si voy es decisión de una hora antes jaja

**Comment by MrTommyGuns** [comment]
Confirmed, voy yo.
Luego pondré por aquí o por el grupo lo que se comente en la reunión.

**Comment by MrTommyGuns** [comment]
Resumen:
Aunque no ha sido nuestro caso, no se pueden realizar las cosas por cuenta de cada asociación por separado y tenemos que apoyarnos entre las asociaciones porque los de arriba nos ven como una sola entidad y si cae alguna o pasa algo nos repercute a todos.
Las estadísticas de la semana de Asociaciones, aunque han sido peores que las de años pasados, teniendo en cuenta las dificultades por el tema creditos, "no han sido tan malas".
Se ha comentado que nos hemos relajado y teníamos que poner más spam para la próxima.
Se han sugerido formulas para mejorar la semana del año que viene. Yo mismo he propuesto que se haga de forma más visual y clara la forma de inscripción, así como no enviar mensajes con emoticonos para evitar que el correo acabe en la bandeja de spam.
Se ha propuesto hacer un grupo de manualidades para que la gente ayude a la creación de carteles, pancartas y diversos materiales.
Se propone crear un grupo para gestionar las asociaciones como un gran conjunto, aunque se aclara que se ha intentado y se sigue barajando.
Y creo que nada más.
Doy por cerrada la issue.
