### ISSUE TITLE
Jam Session 14

### ISSUE THREAD

**Issue by L4g0** [UC3Music/Gestiones-y-Movidas#17]
Como se iba a intentar hacer una jam cada mes, voy creando la issue para ir condicionándonos, decidir fechas y demás. Si no puede ser en noviembre no pasa nada, pero estaría bien hacer por lo menos una antes de Navidad.

Cosas que hay que hacer:

- [x] Decidir fecha (Doodle, mirar disponibilidad del salón de grados)

- [x] Reservar salón de grados

- [x] Hacer y pegar carteles

**Comment by L4g0** [comment]
Creado el Doodle: https://doodle.com/poll/7vi95e7wwz49w8cd

**Comment by L4g0** [comment]
5 de diciembre opción más votada y salón de grados libre

¿Problema? Es un miércoles y quizás no venga tan bien como un viernes

Viernes más votado es el 14 de diciembre, pero coincide ya en período de tutorías/recuperaciones y podría ser que gente no pudiera.

¿Cuál preferís? ¿5 o 14?

**Comment by JorFru** [comment]
Día 5 libre
Día 14 libre
Se usa este calendario para consultar disponibilidad https://arcamm.uc3m.es/agenda.v2/#

Hasta fin de año yo haría una de Jam y otra de #20

**Comment by MrTommyGuns** [comment]
Por mi parte siendo por la tarde lo tengo igual de "mal", así que no podré estar organizandola, como mucho para recoger y demás.
Por otro lado el 5, siendo 6 y 7 fiesta, es como si fuera un viernes... Aunque mucha gente se irá creo que es mejor fecha que el 14, que la gente directamente puede que ni vaya a la uni si es semana de recuperación de clases.
Peroo como siempre, no se sabe.

**Comment by JorFru** [comment]
Yo es que soy muy manco con la guitarra, tengo demasiadas ganas de #20

**Comment by MrTommyGuns** [comment]
Yo veo factible las dos (?)
A mi me renta #20 
Sobre todo que tengo mucha curiosidad de como puede salir y me mola la propuesta...
Una de los Who así para empezar? 😉😉

**Comment by JorFru** [comment]
> Una de los Who así para empezar? winkwink

Lee la issue #20 y te enteras de cómo proponer discos.

**Comment by L4g0** [comment]
Jam confirmada con reserva ya realizada para el **14 de diciembre**

**Comment by L4g0** [comment]
9 carteles pegados por todos edificios menos Sabatini y uno en la asoci.

Por alguna razón han salido azules :confused: 
![image](https://user-images.githubusercontent.com/23212123/49747300-6d64ee00-fca3-11e8-8dea-d0c2dc4a7c82.png)
_Representación Artísitca_

**Comment by David-Estevez** [comment]
Está tremendo ese King África :joy: :joy: :joy:

**Comment by JorFru** [comment]
Maravilloso el trabajo gráfico esta edición.
Gracias @MrTommyGuns @L4g0 por el trabajo de los carteles.

Enhorabuena a todos por el éxito obtenido.
