### ISSUE TITLE
Relación de proyectos para el curso 2018/2019

### ISSUE THREAD

**Issue by L4g0** [UC3Music/Gestiones-y-Movidas#19]
Debemos hacer una lista de los proyectos y una aproximación del material necesario para cada uno. Pongo como **fecha límite el 25 de noviembre** (totalmente casual) para tenerlos todos.

**Comment by David-Estevez** [comment]
Visto #21, yo daría como mucho esta semana para pensar proyectos y prespuestos, ya que luego además habría que reunirse y redactar las propuestas.

**Comment by JorFru** [comment]
Esto quedó hecho.
Hay que esperar hasta mediados de febrero para obtener respuesta.
