### ISSUE TITLE
It's raining euros, amen!!

### ISSUE THREAD

**Issue by David-Estevez** [UC3Music/Gestiones-y-Movidas#21]
Abierto el plazo para presentar proyectos y pedir subvenciones, hasta el **25 de Noviembre**.

![image](https://user-images.githubusercontent.com/1451819/48451764-3090fe80-e7ac-11e8-8504-04030f9f3158.png)

Link a la convocatoria: https://www.uc3m.es/ss/Satellite/Cultura/es/TextoDosColumnas/1371240285442/

Plan de actuación propuesto:
1. Hacer desglose de lo que queremos pedir cada grupo, con precio (rollo presupuesto)
2. Reunión para puesta en común
3. Hacer dos macroroyectos que incluyan el mayor número de cosas posibles de la lista

Yo daría esta semana para sacar los presupuestos y quedaría la semana que viene, para que haya margen para redactar las propuestas.

**Comment by MrTommyGuns** [comment]
Me parece todo correcto.
Tendríamos que hacer doodle para ver cuando quedamos la semana que viene para hacer la reunión, aunque esta vez sugiero que sea en un aula con pizarina o algo así para poder apuntar cosillas, etc...

**Comment by JorFru** [comment]
Como veo que @MrTommyGuns está perro y quiere repartir el trabajo, aquí está el doodle por mi parte. Deadline para redactar y presentar 25 de noviembre.
https://doodle.com/poll/uv6nwccd4yfzmv76

**Comment by JorFru** [comment]
Cosillas entregadas, las copias alacenadas [aquí](https://drive.google.com/drive/folders/1ps6fnszbuGn_I-PN3ob0aCNcYAkDJFDW?usp=sharing)
Las he redactado yo y ha sido corregido por @L4g0 .
La resolución se espera para febrero del 2019. Fecha concreta no se sabe, cada vez tardan más

Prueba de entrega:
![imagen](https://user-images.githubusercontent.com/11017088/48986606-ae8fc680-f117-11e8-8f63-cdcdfb1a8c1f.png)
