### ISSUE TITLE
Memorias proyectos 2017-2018

### ISSUE THREAD

**Issue by David-Estevez** [UC3Music/Gestiones-y-Movidas#22]
Hay que entregar las memorias de los proyectos de este año.

Fecha límite: **23 de Noviembre**

**Texto original**:
2.Sobre la entrega de Memorias:

Una vez realizada la actividad, se debe elaborar un informe o memoria final. El Anexo IV recoge el documento guía para la realización de la memoria*. Este informe / memoria se entregará a través de Aula Global en un periodo no superior a un mes desde la finalización de la actividad. Este plazo no superará en ningún caso la fecha del 30 de junio, para actividades realizadas en el primer semestre y del 23 de noviembre de 2018, para actividades realizadas en el segundo semestre. Se exceptúan los casos recogidos en el artículo 2.2, cuya fecha límite tanto para la entrega de documentación económica como de memoria de actividad será el 11 de diciembre. Pasadas estas fechas, los proyectos serán desestimados y perderán la ayuda concedida. 7. En el supuesto de haber solicitado y obtenido reconocimiento de crédito por la actividad que a su vez ha sido subvencionada, el informe/memoria no se entregará en Aula Global si no que se realizará en los registros de la Universidad.

**Comment by MrTommyGuns** [comment]
Que proyectos con subvención hemos tenido?

**Comment by David-Estevez** [comment]
@SerjSanchez y yo el polytuna

**Comment by JorFru** [comment]
Yo y @MrTommyGuns hemos hecho las de Jam y Hackatón.
#### Entregadas:
- [x] PolyTuna
- [x] JamSession 
- [x] Hackatón 

- ANC desistida

Deberes hechos, muchas gracias a todos.
