### ISSUE TITLE
Limpieza de "despacho"

### ISSUE THREAD

**Issue by L4g0** [UC3Music/Gestiones-y-Movidas#23]
Bueno, creo conveniente quedar un día para organizar un poco el espacio, ya que con el Hackatón y demás movidas lo tenemos todo hecho un poco desastre.

Podríamos hacer también reunión a la vez para hablar de las diversas actividades que se van a hacer este año y conocer quiénes participaremos en cuáles.

Podéis votar la fecha en el Doodle https://doodle.com/poll/scd9iz9cp8idb4qt

**Comment by JorFru** [comment]
Me uno al equipo de limpieza, es importante porque de esto también depende #3

**Comment by L4g0** [comment]
Finalmente esto será hoy lunes 3 a las 19-19:30

**Comment by JorFru** [comment]
Esto quedó hecho ayer y lo de "Y después cervezas" fué soooo fucking real.
Gracias @L4g0 @MrTommyGuns 
Si hay foto del "después" la podéis subir aquí.

**Comment by David-Estevez** [comment]
Hay fotos? :grin:

**Comment by L4g0** [comment]
@David-Estevez Sí

**Comment by David-Estevez** [comment]
:tada: :tada: :tada:

**Comment by L4g0** [comment]
@David-Estevez Creeeeo que hizo @JorFru pero don’t know

**Comment by JorFru** [comment]
Las fotos que pidió @David-Estevez 
Las marcas rosas indican el espacio en el que están confinados nuestros trastos.
![imagen](https://user-images.githubusercontent.com/11017088/49556340-a0a22880-f903-11e8-8391-940ec1c7c17c.png)
![imagen](https://user-images.githubusercontent.com/11017088/49556349-a435af80-f903-11e8-9a58-a3c2fb256fe7.png)
![imagen](https://user-images.githubusercontent.com/11017088/49556354-abf55400-f903-11e8-95da-c6e1f61df455.png)
