### ISSUE TITLE
Presentación de la asociación y proyectos en MakerSpace EPS

### ISSUE THREAD

**Issue by JorFru** [UC3Music/Gestiones-y-Movidas#26]
Nos han invitado a organizar esto:
![imagen](https://user-images.githubusercontent.com/11017088/49594824-f95ed900-f976-11e8-8813-9966787913ca.png)

sería en febrero, después de exámenes.
Como al final no hicimos ninguna actividad en la "Semana de Asociaciones", podríamos aprovechar y hacerlas aquí.
Lo dejo como idea.

**Comment by MrTommyGuns** [comment]
Lo ideal sería hacer un taller más que las charlas que teníamos pensandas, por eso de que la gente que irá quiere hacer cosas maker y tal.
La parte mala es que creo que no tenemos materiales para hacer los talleres de drawdio o algo así, como mucho de reparación de auriculares con lo que queda y yo tengo unos 8 conectores de Ali que puedo donar.

**Comment by JorFru** [comment]
Justo por ser Maker también viene bien hacer una charla para alimentar el SAV de los compañeros.

**Comment by L4g0** [comment]
Yo creo que podemos hacer la charla de cómo grabar en Reaper.

Eso sí, no sé si encaja con lo que buscan desde el maker space...

**Comment by David-Estevez** [comment]
Yo creo que están buscando cosas más maker, y concretamente más relacionadas con hardware y fabricación digital.

No obstante, es cuestión de preguntarles, igual sí que les interesa también.

**Comment by JorFru** [comment]
Fernando el señor que lleva el tema MakerSpace dice:
`hemos reservado la semana del 4-8 de marzo para eventos de las asociaciones, que tal os viene preparar algo para esa semana`

**Comment by MrTommyGuns** [comment]
Yo diría que vamos algo justos 😅
Y los talleres que les pueden interesar a ellos requiere de material que actualmente no tenemos...
Si nos dan materiales podriamos hacer así de improvisado un taller de reparación de auriculares (?)
Sino tal vez alguno de los que teníamos previsto para la semana (ya comentamos que esos no eran muy del rollo que les podría interesar, peroo si les vale podríamos aprovechar)

**Comment by JorFru** [comment]
Reparación de cascos está bien. Yo me ofrezco a impartirlo.

**Comment by MrTommyGuns** [comment]
Yo si es por la mañana también me apunto a echar una mano
También tengo unos cuantos jacks malillos de Aliexpress que puedo donar y para el proposito tiran de sobra

**Comment by MrTommyGuns** [comment]
Esto se ha pasado ya...
Podemos cerrar la issue?

**Comment by JorFru** [comment]
No tan rápido pistolero.
4-8 de marzo

Queda un mes para prepararlo.
En ASROB se están moviendo cosas.
Molaría que en UC3Music también.
Una instalación sonora? ÁlvaroDm7 estaba preparando una en su casa, con tocapelotasbot, os sonará.

**Comment by JorFru** [comment]
Resultó ser más interesante el contenido de ASROB.
Finalmente no nos cogieron ninguna propuesta.
