### ISSUE TITLE
Nosan pouneado

### ISSUE THREAD

**Issue by JorFru** [UC3Music/Gestiones-y-Movidas#27]
![photo_2019-02-03_02-11-18](https://user-images.githubusercontent.com/11017088/52171201-27834e00-2759-11e9-8033-aae62699cc90.jpg)
![photo_2019-02-03_02-11-22](https://user-images.githubusercontent.com/11017088/52171202-29e5a800-2759-11e9-8c30-7a0a96d1f034.jpg)

**Comment by JorFru** [comment]
Cambio de contraseñas general

**Comment by L4g0** [comment]
Ya llevamos un montón de tiempo pero bueno, si queréis las cambiamos...

**Comment by MrTommyGuns** [comment]
Ya están todas las pass cambiadas??
De ser así podemos cerrar la issue

**Comment by JorFru** [comment]
Grasias a los encargados de RRSS en ocuparse de esto.
Cerrando.
