### ISSUE TITLE
Abrir repositorios para las Jams y Sesiones Musicales

### ISSUE THREAD

**Issue by MrTommyGuns** [UC3Music/Gestiones-y-Movidas#28]
Maaybe podríamos hacer un repo solo para las Jams y esto donde subir toda la info?

Ahí podríamos ir posteando todas las cosas de cada actividad, poner algunas fotos para luego hacer las memorias, tener algo de archivo y publicar en las redes a posteriori e incluso si nos calentamos poner el equipo usado, resultado de la actividad, audiencia...

Es una sugerencia peroo ya que nos ponemos me parece una buena opción para tenerlo todo on point.

**Comment by JorFru** [comment]
Buena idea.
Ábrelo y empieza a añadir la información. Yo me uniré después.

**Comment by MrTommyGuns** [comment]
Creado el repo de las Jams: https://github.com/UC3Music/JamSessions

Creado el repo de las Sesiones: https://github.com/UC3Music/SesionesMusicales
