### ISSUE TITLE
Radio GUL

### ISSUE THREAD

**Issue by JorFru** [UC3Music/Gestiones-y-Movidas#30]
GUL de toda la vida ha llevado RadioGUL
Yo les he escuchado y siempre me ha molado su rollo. Creo que encajaríamos.
Además, históricamente siempre nos han dicho que estábamos invitadísimos y que nos iban a llamar para entrevistar.
Se fué posponiendo y al final no ocurrió.

La gente que lleva el programa /dev/random no sólo nos han invitado, nos han insistido en que entremos hasta la cocina. No será una simple entrevista, será un programa completo owneado por UC3Music. Desde allí dentro podremos dar un golpe de estado y hacernos con GUL tipo Caballo de Troya.

Dejo issue abierta para dejar ideas y buscar personas interesadas en representar a esta asociación.
Os dejo demo de los últimos programas que han hecho.
https://www.ivoox.com/podcast-dev-random_sq_f1631391_1.html

**Comment by JorFru** [comment]
¿Alguien se anima con una charla contra el audiofoolery?
Elijamos la pastilla roja...
http://matrixhifi.com/contenedor_ppec.htm

**Comment by L4g0** [comment]
@JorFru I’m fuckin in

**Comment by JorFru** [comment]
Ayer lunes se grabó el primer podcast de UC3Music, que se publicará próximamente en el programa /dev/random de Radio GUL.

![photo_2019-03-26_10-45-39](https://user-images.githubusercontent.com/11017088/54987232-7f4d7100-4fb4-11e9-8cfb-4c27502a1654.jpg)
