### ISSUE TITLE
¿Creamos un canal de SoundCloud para UC3Music?

### ISSUE THREAD

**Issue by JorFru** [UC3Music/Gestiones-y-Movidas#31]
El otro día grabamos un podcast y a parte de publicarse en Radio GUL, molaría tenerlo en alguna plataforma bajo nuestro control.
¿Qué usamos?
- SoundCloud?
- iVoox (coñazo porque pide registarse para usar la app)
- YouTube subido con una imagen fija de Tommy

A parte de podcast quizás algún día queremos subir muestras de sonido de modular, o incluso las jams enteras...
Alguien con ideas?

**Comment by L4g0** [comment]
@JorFru Yo crearía un SoundCloud por tener. El único problem es que la versión gratuita tiene un límite de tiempo que puedes subir en total en tu cuenta.

**Comment by David-Estevez** [comment]
> YouTube subido con una imagen fija de Tommy 

:joy:  :joy:  :joy: :joy:

**Comment by jgvictores** [comment]
Recomendaría:
- SoundCloud: Mola pq hay App. No sabía lo de los límites de tiempo.
- Spotify, ITunes, Youtube Music, etc... (mucho más por comodidad del lado oyente que por el beneficio económico):  Para lo de SHR utilizo [Soundrop](https://soundrop.com/), lo subo a ellos y ellos se encargan de subirlo a todos esos sitios (gratis y llevándose pequeña comisión sobre beneficios)(tb te generan códigos UPC, etc). [Aquí una web](https://aristake.com/post/cd-baby-tunecore-ditto-mondotunes-zimbalam-or) con alternativas. BTW, en Youtube Music suelen poner la portada de la colección/disco (seleccionar bien ^^).

Más ideas:
- Bandcamp, Jamendo o similares, tal vez aún se les pueda dar un uso...
- Para escuchar Podcasts últimamento uso la app "Stitcher". Dejo [link](https://www.stitcher.com/content-providers) para creadores de contenido.

**Comment by L4g0** [comment]
Creado perfil de SoundCloud, para lo que sea que lo utilicemos: [https://soundcloud.com/uc3music](https://soundcloud.com/uc3music).

Email y contraseña habituales.

**Comment by JorFru** [comment]
Subimos el potcas?
Es lo único que tenemos

**Comment by JorFru** [comment]
Podcast subido
https://soundcloud.com/uc3music/primer-podcast-uc3music-para


A ver si grabamos más material, la experiencia estuvo chula.
