### ISSUE TITLE
Feria de asociaciones 26 Abril 2019

### ISSUE THREAD

**Issue by JorFru** [UC3Music/Gestiones-y-Movidas#33]
26 de Abril 2019, césped de Leganés.

Asociaciones de la UC3M EPS organizan una segunda feria de asociaciones. Ya hay una anual allá por octubre, esta es otra, con el objetivo de fomentar las actividaes en asociaciones.

Horario de exposición de 11 a 17h (aunque el doodle diga desde las 10). Media hora por delante y por detrás para montar y desmontar. Aproximadamente. Se puede llegar más tarde, pero el que antes llega pilla mejor sitio.

IMPORTANTE! Se necesitan personas que cubran el evento: estar allí demostrando y vigilando nuestras creaciones e instrumentos.
Actividad extra: hackeo en vivo. Se realizarán tareas parecidas a las que se llevan a cabo en nuestras reuniones, pero puertas abiertas para que el SAV (síndrome del ansia viva) le pique a los visitantes.
Es posible que montemos la música. El guitar hero quizás...
Y después cervezas, entre todas las asociaciones.

Se propone Doodle para indicar disponibilidad.
Votad!
https://doodle.com/poll/ufy8tsynh5tsqp2w

**Comment by David-Estevez** [comment]
https://github.com/asrob-uc3m/actas/issues/191#issuecomment-480289134

**Comment by JorFru** [comment]
¿Qué os parece ponernos al lado de ASROB y así compartir recursos humanos?
Empalmar las mesas y cuidar nuestros proyectos mutuamente.

**Comment by David-Estevez** [comment]
:+1:

**Comment by MrTommyGuns** [comment]
Yooo tengo que mirar bien mis mierdas, peroo de poder, por la mañana.
Lo del stand con Asrob contaba con ello

**Comment by MrTommyGuns** [comment]
Como parte del SAV lo mismo podríamos intentar arreglar la batería y movidas del rollo, hacer cables o warever 🤔🤔

**Comment by JorFru** [comment]
he colocado los carteles en nombre de UC3Music

**Comment by MrTommyGuns** [comment]
Maravillosoooo!!

**Comment by MrTommyGuns** [comment]
Maravillosoooo!!

**Comment by L4g0** [comment]
Finalizada la feria con éxito.
