### ISSUE TITLE
Semana de Asociaciones 2019

### ISSUE THREAD

**Issue by L4g0** [UC3Music/Gestiones-y-Movidas#36]
Nos ha llegado un correo de Montserrat (la nueva África) sobre la Semana de Asociaciones:

> Queremos informaros de las fechas de la VI Semana de las Asociaciones que se celebrará del 30 de septiembre al 04 de octubre, en los campus de Leganés, Getafe y Colmenarejo.
>
> La VI Semana de Asociaciones quiere reflejar el entusiasmo de las Asociaciones de Estudiantes de la UC3M y de la Delegación de Estudiantes por mostrar el importante trabajo que desarrollan en la universidad. Se realizarán talleres, conferencias, video-forum, mesas redondas…
>
> Como en años anteriores, tenemos que proceder a la reserva de espacios, así como a la publicación en web y Aula Global de las actividades.
> 
> Para conocer el número de asociaciones que participará en estos actos, y las necesidades de las mismas, nos gustaría nos comuniquéis vuestra asistencia, mediante el formulario que os adjunto, antes del 10 de julio. Nos gustaría contar con 11/12 actividades en cada campus. Adjunto los cuadrantes horarios de los diferentes campus para que los tengáis en cuenta.

TL;DR:

* Este año se va a volver a organizar una Semana de Asociaciones, pero no vamos a tener a África para presionarnos a proponer cosas porque ya no lleva el tema.
* Aún asi, es importante organizar alguna charla / taller porque hay que mostrar que las Asociaciones estamos activas para luego poder optar a subvenciones, etc y que no reduzcan / cierren el programa de Asociaciones.
* Nos piden propuestas de actividades **antes del 10 de Julio**

Sé que este año muchos no vamos a estar aquí por esas fechas, pero estaría bien que comentáseis por aquí si vais a estar o no y si se os ocurre alguna charla / taller que dar, a ver si sacamos algo adelante.

**Comment by JorFru** [comment]
Done
