### ISSUE TITLE
Talleres Semana de Asociaciones 2019

### ISSUE THREAD

**Issue by JorFru** [UC3Music/Gestiones-y-Movidas#37]
Durante la semana se realizan varios talleres organizados por las asociaciones.
Será la primera semana de octubre.
Si la fecha os viene mal, se puede realizar el taller fuera de la semana, por ejemplo solicitando el sótano de la biblioteca mediante reserva de espacios o bien haciéndolo en el makespace.

A saber por parte de UC3Music:

- Taller de sonido en directo
- Taller de grabación en estudio

Viene de https://github.com/UC3Music/Gestiones-y-Movidas/issues/8

**Comment by MrTommyGuns** [comment]
Yo si que la haría, nos aseguramos que va a asistir gente yo creo.
Este año la que teníamos @L4g0 y yo no está preparada pero yo creo que se puede improvisar un poco si tal y listo...
El tema horario sería importante cuadrarlo bien, no sé como estará organizado este año.
Sería optimo contar con los instrumentos de la asociación para ese día y no tener que venir cargados.

**Comment by L4g0** [comment]
## Actividades Semana de Asociaciones

- CÓDIGO 14 - **2 de Octubre 16:00-19:15h**: UC3Music. Cómo sonorizar un concierto (3h) (Aula 3.S1.08) por @JorFru 

- CÓDIGO 19 - **4 de Octubre 16:00-19:15h**: UC3Music. Cómo grabar una canción (3h) (Aula 3.S1.08) por @MrTommyGuns y @L4g0 

Ambas han sido añadidas al Google Calendar.

**Comment by JorFru** [comment]
![photo_2019-10-08_12-12-51](https://user-images.githubusercontent.com/11017088/66387796-fbddf500-e9c4-11e9-9402-8e8d81002e99.jpg)
![photo_2019-10-08_12-12-52](https://user-images.githubusercontent.com/11017088/66387798-fbddf500-e9c4-11e9-887b-3065f7905e9e.jpg)
![photo_2019-10-08_12-12-53](https://user-images.githubusercontent.com/11017088/66387800-fbddf500-e9c4-11e9-9f1b-6f98aed2f34c.jpg)
