### ISSUE TITLE
Feria de asociaciones 2019

### ISSUE THREAD

**Issue by JorFru** [UC3Music/Gestiones-y-Movidas#38]
Dentro de la semana de asociaciones se organiza la Feria de Asociaciones.
Será el 1 de Octubre en leganés. Patio como siempre.
En Getafe también, just information, 4 Octubre.

Hay que sacar los cacharrillos a pasear.

Apúntense en la issue.
Si no vamos a tener disponibilidad entre todos para cubrir el día entero se puede mirar hacer un doodle.

**Comment by MrTommyGuns** [comment]
Yo me apunto al tema, lo malo es que cae en miércoles y tengo unas cuantas asigntaruas distribuidas a lo largo del día.
Así que por mi parte un doodle para saber el horario de todos y gestionar quien se encargar en cada franja horaria y que al menos haya una persona en ese rato está guay,

**Comment by JorFru** [comment]
Atención cae en martes.
Revisa.

**Comment by JorFru** [comment]
Yo estoy disponible desde las 13 hasta cierre.
Supongo que la hora de montar será a las 10:30 o así.

**Comment by MrTommyGuns** [comment]
Yo los miércoles tengo clase de 9-11 y de 15-17, a no ser que surja algún imprevisto, estaré el resto de horas.

**Comment by L4g0** [comment]
Es MARTES 1 de octubre @MrTommyGuns , yo puedo el día entero básicamente

**Comment by JorFru** [comment]
![photo_2019-10-08_12-11-58](https://user-images.githubusercontent.com/11017088/66387745-e23cad80-e9c4-11e9-988f-2edb03c2736f.jpg)
![photo_2019-10-08_12-11-59](https://user-images.githubusercontent.com/11017088/66387746-e2d54400-e9c4-11e9-9ece-745691a38138.jpg)
![photo_2019-10-08_12-12-02](https://user-images.githubusercontent.com/11017088/66387747-e2d54400-e9c4-11e9-87d6-5fa4d7f72529.jpg)
![photo_2019-10-08_12-12-03](https://user-images.githubusercontent.com/11017088/66387748-e36dda80-e9c4-11e9-8b8d-be2502497c53.jpg)
