### ISSUE TITLE
Acta Reunión 16/09/19

### ISSUE THREAD

**Issue by MrTommyGuns** [UC3Music/Gestiones-y-Movidas#39]
Temas a tratar:

- Conoce UC3Music
- Proyectos (Mirada general, propuestas, etc)
- Subvenciones y pastuki
- Calendario de Google
- Radio UC3Music
- Jams y quedadas Musicales
- Mirar Issues
- Guitarra y Bajo
- El Evento y Hackatón
- Elección nuevos cargos(?) - Voluntarios?

**Comment by MrTommyGuns** [comment]
Propuesta: Jam Session en el patio (en acustico o warever)

**Comment by MrTommyGuns** [comment]
Fijada fecha para montaje de la guitarra y el bajo de Uc3Music el lunes 23/9/19

**Comment by MrTommyGuns** [comment]
Usaremos el calendario "Eventos de UC3Music" de la cuenta de gmail de la asociación.
Lo compartiremos de forma pública.

**Comment by L4g0** [comment]
Reunión finalizada con éxito.

**Comment by JorFru** [comment]
Echo de menos el acta de reunión pero la verdad es que da un poco de pereza.
Creo que sorry.

**Comment by David-Estevez** [comment]
> Echo de menos el acta de reunión pero la verdad es que da un poco de pereza.
Creo que sorry.

:cry:
