### ISSUE TITLE
Feria de Asociaciones 2018

### ISSUE THREAD

**Issue by L4g0** [UC3Music/Gestiones-y-Movidas#4]
Abro este issue para poner todo lo relacionado con la **Feria de Asociaciones** de este año.

Se celebrará el **miércoles 26 de septiembre** en el jardín de Leganés. Se podría considerar ir a Getafe (desconozco el día) si hay gente dispuesta a estar en el stand.
En Lega deberíamos ir turnándonos ya que la feria es de 10 a 19:30. Si podéis estar a las 9 para montar estaría genial.

Qué haremos:

- Exponer cacharros varios

- Guitar Hero (falta comprar alguna guitarra)

- Sello impreso 3D? Como idea podríamos tener un sello personalizado para la gymkana

- Ideas para la prueba de la gymkana:

  - Tocar cumpleaños feliz u otra canción con el Drawdio

  - Elegir la resistencia THT del valor que le pidamos

  - La mítica de adivinar la canción tocada por 2Cellos

  - Una persona tararea una canción con el idiotizador puesto (escucha su voz con retardo) y otra persona tiene que adivinarla

Poned aquí las ideas que tengáis y tenemos que acabar decidiendo una (también se me ocurre tener varias y si no son capaces de pasar una dejarles intentar otra).

Espero vuestras opiniones 😄

**Comment by David-Estevez** [comment]
Sugiero plantar el stand al lado del de ASROB, así será mejor para turnarnos, ya que podríamos estar en los dos stands a la vez.

**Comment by MrTommyGuns** [comment]
Yo puedo encargarme de ir a las 9 (aunque me duela y mucho) y obviamente nos ponemos al lado de Asrob e intentamos poner 2 mesas para cada asoci o 3 para las 2
Que si se monta el guitar hero, cacharros  impresoras, etc... Vamos a estar fastidiados

**Comment by L4g0** [comment]
Yo estaré a las 9 sin fallo. Lo de montar al lado de ASROB obvio 👌

**Comment by MrTommyGuns** [comment]
A mi la actividad que más me mola es la del drawdio, seguida de la de las resistencias.
Pero la del drawdio tiene que ser diver

**Comment by L4g0** [comment]
Bueno, después de una feria con una buena cantidad de nuevos inscritos, podemos cerrar esta issue
