### ISSUE TITLE
Nos han invitado a la Bilbao MakerFaire

### ISSUE THREAD

**Issue by JorFru** [UC3Music/Gestiones-y-Movidas#40]
El año pasado nos invitaron y no fuimos.

Alguien se anima a ir y representar a UC3Music llevando robotillos? Pagan todo el viaje y el alojamiento.

Será los días 1, 2 y 3 de Noviembre, de viernes a domingo.
Más info: https://bilbao.makerfaire.com/

Hay que rellenar el C4M en caso que alguien se anime.

**Comment by JorFru** [comment]
Yo no puedo

**Comment by L4g0** [comment]
¿Te refieres a ASROB o UC3Music? Porque igual el copy-paste se te ha ido.

**Comment by JorFru** [comment]
Ambas estamos invitadas.

**Comment by JorFru** [comment]
Ah, ya sé.
Edito

**Comment by L4g0** [comment]
Justo el finde siguiente es la OSHWDem, pero podría planteármelo. Dependería de si tengo exams y esas cosas tb. No es un no, tampoco un sí.

**Comment by JorFru** [comment]
Tienes hasta el día 27 de septiembre para pensártelo

**Comment by David-Estevez** [comment]
Yo tampoco puedo :(

**Comment by JorFru** [comment]
Feria desestimada
