### ISSUE TITLE
Montaje de la Guitarra y el Bajo DIY

### ISSUE THREAD

**Issue by MrTommyGuns** [UC3Music/Gestiones-y-Movidas#41]
Quedó fijada la fecha para este proyecto para el 23/09/19 en la última reunión de 17h a 21h.

**UPDATE**: Se ha actualizado la fecha del montaje al 30/09/2019

Se realizará en el espacio de trabajo de Asrob (1.0.B06). Para ello se ha solicitado dicho espacio y ha sido cedido (Ver issue correspondiente [aquí](https://github.com/asrob-uc3m/actas/issues/202)).

Está previsto que aparezcan pintadas y en un estado óptimo para su montaje.

El objetivo a parte del montaje, será observar y aprender sobre su construcción.

Como sugerencia/ampliación de la actividad, propongo realizar el ajuste apropiado para que queden calibrados de la mejor forma posible.

**Comment by MrTommyGuns** [comment]
Queda aplazada la reunión de forma indefinida debido a la necesidad de que la pintura quede fijada correctamente

**Comment by L4g0** [comment]
Se ha aplazado dicha reunión, pero hemos mirado cosas de la batería que se encuentran recogidas aquí: https://github.com/UC3Music/electrotupah/issues/4 #

Reunión aplazada para el 30/09/2019

**Comment by JorFru** [comment]
![photo_2019-10-08_12-16-33](https://user-images.githubusercontent.com/11017088/66388037-98a09280-e9c5-11e9-9f85-b3f62f6b57ee.jpg)
![photo_2019-10-08_12-16-33 (2)](https://user-images.githubusercontent.com/11017088/66388038-99392900-e9c5-11e9-980f-51d0f9764795.jpg)
![photo_2019-10-08_12-16-37](https://user-images.githubusercontent.com/11017088/66388039-99392900-e9c5-11e9-9522-0e9ec73bbe47.jpg)
![photo_2019-10-08_12-16-38](https://user-images.githubusercontent.com/11017088/66388040-99392900-e9c5-11e9-84b0-b25555e2d800.jpg)
![photo_2019-10-08_12-16-39](https://user-images.githubusercontent.com/11017088/66388043-99d1bf80-e9c5-11e9-945c-863145fb713c.jpg)
![photo_2019-10-08_12-16-40](https://user-images.githubusercontent.com/11017088/66388045-99d1bf80-e9c5-11e9-9e1b-3fdf31e17604.jpg)
![photo_2019-10-08_12-16-41](https://user-images.githubusercontent.com/11017088/66388046-99d1bf80-e9c5-11e9-955a-07c6df758a86.jpg)
![photo_2019-10-08_12-16-42](https://user-images.githubusercontent.com/11017088/66388047-99d1bf80-e9c5-11e9-8781-55e655dca0a9.jpg)
![photo_2019-10-08_12-16-43](https://user-images.githubusercontent.com/11017088/66388048-9a6a5600-e9c5-11e9-818e-948d3f9af546.jpg)
![photo_2019-10-08_12-16-46](https://user-images.githubusercontent.com/11017088/66388049-9a6a5600-e9c5-11e9-99ba-7581fc884fa2.jpg)
![photo_2019-10-08_12-16-47](https://user-images.githubusercontent.com/11017088/66388050-9a6a5600-e9c5-11e9-9ac5-ba37622c6060.jpg)
![photo_2019-10-08_12-16-49](https://user-images.githubusercontent.com/11017088/66388052-9a6a5600-e9c5-11e9-86d2-e7b15c57614d.jpg)
![photo_2019-10-08_12-16-50](https://user-images.githubusercontent.com/11017088/66388053-9b02ec80-e9c5-11e9-97fc-d5ebc0e4f5a5.jpg)
![photo_2019-10-08_12-16-51](https://user-images.githubusercontent.com/11017088/66388054-9b02ec80-e9c5-11e9-9e6e-36dff347826a.jpg)
![photo_2019-10-08_12-16-59](https://user-images.githubusercontent.com/11017088/66388055-9b02ec80-e9c5-11e9-8b61-5f35c4cc3c08.jpg)
![photo_2019-10-08_12-11-58](https://user-images.githubusercontent.com/11017088/66388063-a2c29100-e9c5-11e9-9975-00b171744a42.jpg)
![photo_2019-10-08_12-12-02](https://user-images.githubusercontent.com/11017088/66388064-a2c29100-e9c5-11e9-8927-e1e54c7c0124.jpg)

**Comment by David-Estevez** [comment]
@JorFru vuelca las fotos al drive tron! así las tenemos para carteles/memorias/eventos/postales/merch/etc.
