### ISSUE TITLE
Mejoras batería

### ISSUE THREAD

**Issue by L4g0** [UC3Music/Gestiones-y-Movidas#42]
Bueno, debemos organizar los pedidos de material para la batería:

Aquí los detalles y temas hablados: https://github.com/UC3Music/electrotupah/issues/4

Importante serían los cables, que añadiría a los XLR y demás que se pidan para taller soldadura/para las jams.

También filamento 3D y alguien debería hacer el diseño 3D del casco, que no tengo ni idea.

En caso de elegir la estructura de madera habría que ir a comprarla también.

**Comment by MrTommyGuns** [comment]
Para el filamento 3D propongo usar PET-G que no parece complicado de imprimir y es mecánicamente más resistente que el PLA.

**Comment by David-Estevez** [comment]
> En caso de elegir la estructura de madera habría que ir a comprarla también.

¿Y no sería mejor una estructura de perfiles de aluminio, que serían más fáciles de desmontar para hacerla "portable"? @JorFru tiene experiencia con el tema...

**Comment by JorFru** [comment]
Opino que la estructura tiene que quedarse de PVC
Tiene defectos que se pueden arreglar con un poco de ingenio.
Pero una estructura nuevame parece una inversión de tiempo muy grande que no nos podemos permitir por el momento.

**Comment by David-Estevez** [comment]
Aunque no se termine el diseño, si hay dinero siempre se pueden comprar los materiales. Comprar por ejemplo la perfilería y dejarla apartada hasta que haya tiempo para diseñar unos soportes.

**Comment by JorFru** [comment]
Valoro comprar perfilería en la convocatoria del 2020

**Comment by JorFru** [comment]
actualmente este tema se está hablando en su respectiva issue

https://github.com/UC3Music/electrotupah
