### ISSUE TITLE
Viaje a la OSHWDem /A Coruña/ 9-Nov-2019

### ISSUE THREAD

**Issue by L4g0** [UC3Music/Gestiones-y-Movidas#43]
Que se apunten a continuación las personas interesadas en viajar. Y ya veremos la forma de conseguir las ayudas necesarias.

Tened en cuenta de que hay plazas tanto en UC3Music como en ASROB (https://github.com/asrob-uc3m/actas/issues/200). Ya nos distribuiremos cómo sea.

**Comment by JorFru** [comment]
Yo voy 

Recordad el voto por correo

**Comment by MrTommyGuns** [comment]
Yo me apunto manitos!

A que te refieres por el voto por correo @JorFru ?

**Comment by JorFru** [comment]
Que si viajas a la OSHWDem no puedes votar en las generales del 10N

**Comment by MrTommyGuns** [comment]
Aaaaah ostias vale!! 

No me acordaba que hay que votar cada 3 meses, que despiste

**Comment by MrTommyGuns** [comment]
Ya se puede solicitar el voto por correo mans

**Comment by L4g0** [comment]
Se acabó con buenos resultados y una Jurassic Jam.

Fotos del evento por acá:
https://photos.google.com/share/AF1QipPqVaSdQ4kUH9Svj_C0gkLOZlosiwlzd9Z11j-NwOX8I2cVa4-LuKnjRd4ASAHMSg?key=ejZPTUxqMXVXNXFZLU1RWDRRaVZtNm5jcXl5QUZR
