### ISSUE TITLE
El Evento/Hackhatón con ASROB y GUL

### ISSUE THREAD

**Issue by L4g0** [UC3Music/Gestiones-y-Movidas#46]
Bueno, se ha pensado hacer el evento el 30 de octubre y tenemos que:

- [ ]  Comprar materiales
- [ ] Elegir prueba(s)
- [ ] Buscar patrocinadores (¿pizza? o tal vez el GoTaco jajaj)

¿Seguiremos adelante? Deberíamos aprovechar que se ha propuesto como actividad del año 2019.

Les interesa esto a @JorFru @MrTommyGuns

**Comment by MrTommyGuns** [comment]
We're so f*cked, tenemos una semana... Y no hemos pedido ni los componentes...
Había ya algo pedido del proyecto hackaton???

**Comment by L4g0** [comment]
Ooooooootra opción sería montarlo la semana del 4? Aunque tenemos la OSWHDem cerquita

**Comment by MrTommyGuns** [comment]
Peroooo cuando es la fecha de entrega de las memorias??? Porque estoy tooo perdido!

**Comment by David-Estevez** [comment]
Acordarse de que la última vez se usó stock de ASROB que igual interesaba reponer en señal de agradecimiento... :roll_eyes:

**Comment by JorFru** [comment]
F

**Comment by MrTommyGuns** [comment]
F
