### ISSUE TITLE
Memoria de Asociaciones 2019

### ISSUE THREAD

**Issue by David-Estevez** [UC3Music/Gestiones-y-Movidas#48]
Ha llegado el momento del año que tod@s esperábamos: la entrega de la Memoria de Asociaciones de 2019

# Resumen
* **Qué hay que hacer**:  Rellenar y entregar la Memoria de Asociaciones, que incluye todo lo que hemos hecho este año.
* **Cuándo es el plazo de entrega**: el plazo acaba el **18 de Diciembre de 2018**.
* **Quién se debería encargar de este ~~marrón~~ trámite**: lo suyo sería la Junta, que son los que más enterados están de las cosas. Pero cuantos más seamos para escribir cosas, mejor.
* **Por qué hay que hacer esto**: es un trámite obligatorio para todas las asociaciones de la universidad. No cumplirlo supone la baja en el registro de asociaciones.

**Comment by L4g0** [comment]
Hecho!
