### ISSUE TITLE
Hacer saber a la gente de la Newsletter que seguimos vivos

### ISSUE THREAD

**Issue by L4g0** [UC3Music/Gestiones-y-Movidas#5]
Habría que mandar una newsletter con un resumen de la reunión, con un link al nuevo sistema de issues, animarles a que se metan al grupo de tg, etc.

**Comment by MrTommyGuns** [comment]
Yo diría que la newsletter está ya muerta... Al que le interesa la asociación ya está en el grupo y al que le interesen talleres y Jams no tiene más que seguirnos en las redes...

Así en conclusión me parece que no hace falta.

**Comment by JorFru** [comment]
Yo creo que Google Groups es ya una vieja gloria.
Tuvo su época de oro con [CloneWars](https://groups.google.com/forum/#!forum/asrob-uc3m-impresoras-3d) con 15.000 topics. Fue un proyecto nacido en la UC3M, concretamente en ASROB.

La lista de correos mola porque tú decides si la quieres o no. Entonces nadie debería de quejarse de intrusismo, porque puedes darte de baja en un click. En redes sociales puedes hacer lo mismo. Seguir o no seguir según te apetece escuchar a estos pavos.
El problema es que hay que dar difusión en redes y además en el correo, lo cual implica un poco más de tiempo.

**Comment by David-Estevez** [comment]
La idea original del Google Groups no era ser un Newsletter, sino un lugar de discursión, de asistencia técnica y de compartir frikadas que descubrimos. Como tal fracasó, porque a día de hoy no lo usamos ni los que lo creamos. 

En su lugar ha resurgido el Telegram, que actualmente cumple esas funciones y bastante bien. Por tanto mi propuesta es cerrar el Google Groups.

**Comment by MrTommyGuns** [comment]
Puess yo diría de o chaparlo o dejarlo ahí, sin más y cerrar esta issue...

Al final lo dicho, entre redes, el grupo de telegram y la forma de llevar el github que estamos adoptando es más que suficiente.

**Comment by L4g0** [comment]
Yo lo de Google Groups lo chaparía, pero la Newsletter tampoco hace daño. Eso sí, da pereza redactarla.

**Comment by JorFru** [comment]
Yo chapaba. Que la gente se enchufe a las RRSS. El formato foro es feucho.
