### ISSUE TITLE
Representar a UC3Music en la Bilbao Maker Faire

### ISSUE THREAD

**Issue by JorFru** [UC3Music/Gestiones-y-Movidas#6]
Eché el Call4Makers y nos han aceptado.
![imagen](https://user-images.githubusercontent.com/11017088/45962683-b94bb380-c021-11e8-85e8-fef8aa7f84ef.png)
Ofrecen dos plazas, con viaje, comida y alojamiento pagado.

Sugerí que UC3Music llevaría sus típicos cacharros electrónicos.
### Y otra persona que se encargue de impartir el taller de Drawdio.

Es necesario listar las personas interesadas en ir y debatir un método de elegir a los afortunados.

**Comment by L4g0** [comment]
Yo creo que lo voy a tener complicado para ir, estoy tanteando ir a unos conciertos ese finde...

Not 100% sure

**Comment by JorFru** [comment]
Necesito saber el nombre del beneficiario de un viaje pagado a Bilbao.
Urgente.

**Comment by JorFru** [comment]
@L4g0 mira si te renta cambiar tus conciertos por ir al BIME. La única banda destacable es MGMT, no es un gran cartel este año.

Regalan entradas la organización de la MF a los Makers.

**Comment by JorFru** [comment]
Cancelado el viaje por falta de personal.
Centraremos nuestros esfuerzos en la OSHWDem18 https://github.com/UC3Music/Gestiones-y-Movidas/issues/10
