### ISSUE TITLE
Jameo que te veo

### ISSUE THREAD

**Issue by MrTommyGuns** [UC3Music/Gestiones-y-Movidas#7]
Estaría guay ir pensado en hacer una Jam de principio de curso después de la semana de asociaciones

**Comment by JorFru** [comment]
Yo la segunda semana de octubre la tengo bastante disponible para llevar mi mezcladora y organizar un poquiejo.

**Comment by L4g0** [comment]
Cosas que hay que hacer:

- [x] Decidir fecha (Doodle, mirar disponibilidad del salón de grados)

- [x] Reservar salón de grados

- [x] Hacer y pegar carteles

**Comment by L4g0** [comment]
Voten fecha aquí! https://doodle.com/poll/zqtunkvtzm68c62y

**Comment by L4g0** [comment]
Ha ganado el **jueves 25 de octubre de 4 a 8**. Ahora toca hacer la reserva del salón de grados y pensar un cartel.
¿Queremos seguir con el mismo formato de cartel o lo cambiamos?
En caso de seguir, ¿a qué artista ponemos? Podemos votarlo en Telegram

**Comment by MrTommyGuns** [comment]
Yo voto por el mismo formato

**Comment by L4g0** [comment]
Está enviada la petición de reserva del Aula de Grados. Espero confirmación (será el día anterior???)

**Comment by L4g0** [comment]
¡Ya tenemos cartel!
![jamsession13](https://user-images.githubusercontent.com/23212123/47123195-74aae500-d27a-11e8-97b9-49bcc2199bfe.jpg)

**Mañana** de 2 a 3 estoy disponible para pegarlos con quien quiera unirse

**Comment by JorFru** [comment]
@L4g0 es justo la reunión de FENIX, que es de 13 a 15h

Si te pasas por ahí me recojes de la oreja. Si no, es posible que se me olvide :'-(

**Comment by JorFru** [comment]
UPDATE me he puesto una alarma en el móvil xD

**Comment by JorFru** [comment]
Hoy se han colgado 8 (ocho) carteles a color tamaño A3.
El lunes repetiremos expedición y paga Jorge

**Comment by L4g0** [comment]
He creado un evento de fb para intentar moverla un poco, yo suelo encontrar eventos interesantes por ahí e igual a alguien le mola y se viene.

Link aquí: https://www.facebook.com/events/168015890811357/

**Comment by L4g0** [comment]
Siguiente tarea es subir vídeo(s) a YouTube (me autoasigno) y algunas fotillas por ahí y se podrá cerrar la issue.

**Comment by L4g0** [comment]
Vídeo subido! https://youtu.be/IhpTuSj1Xuk
