### ISSUE TITLE
Hacer Charlas previstas para la V Semana de Asociaciones

### ISSUE THREAD

**Issue by L4g0** [UC3Music/Gestiones-y-Movidas#8]
Parece ser que han suspendido todas las charlas con menos de 10 inscritos, lo que incluye las dos nuestras que teníamos planeadas. En Leganés **solo han sobrevivido 6 actividades**:

LUNES 1 DE OCTUBRE
Se caen todas, incluso la conferencia inaugural.

MARTES 2 DE OCTUBRE
1) Código 45. Charla Python 101. De 11 a 12.30h. Biblioteca Rey Pastor. Sala de Video 3.S1.08. Organiza: Asociación GUL UC3M

2) Código 46. 13:00 - 14:30h. Taller: La realidad de las prácticas. Biblioteca Rey Pastor. Sala de Video 3.S1.08. Organiza: Mujeres UC3M, Ada Lovelace, Voces UC3M, Con Ciencia, LGBT UC3M y Agrupación Carlos Marx

3) Código 47. 15:00 – 16.30h. Charla: Introducción al Feminismo. Biblioteca Rey Pastor. Sala de Video 3.S1.08. Organiza: Asociación Feminista Ada Lovelace

MIÉRCOLES 3 DE OCTUBRE
4) Código 52. 13:00 - 14:30h. Taller: Salud Sexual. Biblioteca Rey Pastor. Sala de Video 3.S1.08
Organiza: Asociación Feminista Ada Lovelace

5) Código 53. 15:00 - 18:00h.Taller: Iniciación a los Juegos de Mesa. Aula 2.3.A03 (2 SELLOS)
Organiza: Asociación Iñigo Montoya

JUEVES 4 DE OCTUBRE

6) Código 57. 13:00 - 16:00h. Taller: Juego de Mesa Feminista. Edificio y Aula por determinar (2 SELLOS). Organiza: Asociación Iñigo Montoya y Asociación Feminista Ada Lovelace

Seguramente la charla del Reaper la organizemos @MrTommyGuns y yo para otra ocasión.

**Comment by MrTommyGuns** [comment]
Preguntamos a África el número de apuntados a nuestras charlas (por curiosidad) y así vemos a la gente que le interesaba o si alguien de las personas a las que no le ha dado palo apuntarse se ha apuntado (?)

**Comment by L4g0** [comment]
Puede estar interesante hacer alguno de los talleres en el Maker Space.

También se podría preparar una charla explicando cómo funciona la asoci. O meter momento spam en un taller, que lo veo más viable.

![image](https://user-images.githubusercontent.com/23212123/49594314-e0a1f380-f975-11e8-85ab-fc3274cce7ac.png)

**Comment by JorFru** [comment]
Mejor issue nueva. #26 
Esta issue la dejamos como bug y no la volvemos a abrir.

**Comment by L4g0** [comment]
Esto se puede hacer al principio del próximo curso para alimentar el SAV de gente que venga nueva a la uni o que no nos conocieran

**Comment by JorFru** [comment]
Continúa en https://github.com/UC3Music/Gestiones-y-Movidas/issues/37
