### ISSUE TITLE
Actualizar página web

### ISSUE THREAD

**Issue by L4g0** [UC3Music/Gestiones-y-Movidas#9]
Nuestra página web (http://music.uc3m.es/) necesita una actualización del contenido o incluso un rediseño más moderno. Me ofrezco a ayudar en lo que haga falta, aunque desconozco de cómo está gestionada ahora mismo.

Cosas que mejoraría (algunas puede que sean técnicamente imposibles)

- [ ] Actualizar contenido

- [ ] Cambiar foto portada (hacer más en jams nuevas)

- [ ] Certificado digital para hhtps? Si se puede creo que sería lo suyo tenerlo.

Cualquier otra cosa decid y se añadirá a esta lista.

Por cierto, no sé si esta issue pertenece aquí o debería migrarse al repo de la página: https://github.com/UC3Music/UC3Music.github.io

Salu2

**Comment by L4g0** [comment]
![image](https://user-images.githubusercontent.com/23212123/46439444-e9e9c680-c760-11e8-9b73-8ff8f4493b6c.png)

 Por favor, esto no es serio en 2018 😆

**Comment by JorFru** [comment]
Jejeje de acuerdo en todos los puntos.
La issue convendría ponerla en el repo de la página web, yes.
Te pones con ello @L4g0 ?

**Comment by jgvictores** [comment]
Os dejo aquí una herramienta sencilla para mover issues entre repos https://github-issue-mover.appspot.com 😊

**Comment by MrTommyGuns** [comment]
Como comentó @JorFru en el grupo también habría que añadir un enlace al calendario de Uc3Music donde poner las movidas que hagamos y la gente se pueda meter a verlo

**Comment by L4g0** [comment]
Migrado al repo de la web

**Comment by JorFru** [comment]
Migrado aquí https://github.com/UC3Music/UC3Music.github.io/issues/21
